### ISSUE TITLE
javamods-linux-server.sh not work

### ISSUE THREAD

**Issue by ProjectSky** [quarantin/javamods#1]
#### I just try to use this project in the server, but startup script is not working, any help?

* server version : 41.65
* OS: ubuntu 20.04

#### stack trace
```
64-bit java detected
Exception in thread "main" java.lang.NoClassDefFoundError: se/krka/kahlua/vm/Platform
        at zombie.javamods.Main.<init>(Main.java:26)
        at zombie.javamods.Main.main(Main.java:69)
Caused by: java.lang.ClassNotFoundException: se.krka.kahlua.vm.Platform
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
Unrecognized option: -XstartOnFirstThread
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by quarantin** [comment]
Yeah sorry it's not working for MP yet, only SP. I still have to figure out how to start the server with javamods enabled. The server script was just for me to do my testing, because when 41.60 was released I couldn't find a way to have my custom mods on the server unless they're uploaded to steam workshop. I'll let you know when I get something that works on MP. In the meantime please be patient.

**Comment by quarantin** [comment]
By the way, are you willing to develop Java mods for the game? Or to develop Lua mods that use the features from a Java mod?  At the moment there're no java mods for servers anyway, so unless you're planning to develop your own mods this framework will be completely useless to you as a end-user.

**Comment by ProjectSky** [comment]
of course, I currently implement some functions by decompiling class files, i think this is too complicated and difficult to maintain.
i need a loader to load external class files.

**Comment by quarantin** [comment]
Nice! I'm looking for modders who need java mods. Are you available on Discord to discuss this? I could help you getting it to work for server without actually making a release. I'm co` on TIS server. Feel free to DM me.
